[tool.poetry]
name = "introduction-pytest"
version = "0.1.0"
description = ""
authors = ["Guilhem"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.2.0"
random2 = "^1.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
